### ISSUE TITLE
一键安装命令失败

### ISSUE THREAD

**Issue by Jonnyan404** [Thaolga/openwrt-nekobox#2]
```
curl: (3) nested brace in URL position 333:
https://github.com/Thaolga/openwrt-nekobox/releases/download/{"url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/179912321","assets_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/179912321/assets","upload_url":"https://uploads.github.com/repos/Thaolga/openwrt-nekobox/releases/179912321/assets{?name,label}","html_url":"https://github.com/Thaolga/openwrt-nekobox/releases/tag/1.4.6","id":179912321,"author":{"login":"Auroraxpm","id":73517
Download failed!
```

**Comment by Auroraxpm** [comment]
wget -O /root/nekobox.sh https://mirror.ghproxy.com/https://raw.githubusercontent.com/Thaolga/openwrt-nekobox/nekobox/nekobox.sh  && chmod 0755 /root/nekobox.sh && /root/nekobox.sh

**Comment by Jonnyan404** [comment]
> wget -O /root/nekobox.sh https://mirror.ghproxy.com/https://raw.githubusercontent.com/Thaolga/openwrt-nekobox/nekobox/nekobox.sh && chmod 0755 /root/nekobox.sh && /root/nekobox.sh

我是在脚本面板上执行1，然后报错如上

**Comment by Auroraxpm** [comment]
先安装6在安装1

**Comment by Jonnyan404** [comment]
> 先安装6在安装1

Unsupported architecture: armv7l

这意思就是不支持喽，如果不打算支持的话，请直接关闭此issue，谢谢

**Comment by Auroraxpm** [comment]
安装curl在安装

**Comment by Jonnyan404** [comment]
> 安装curl在安装

curl 8.7.1 (arm-openwrt-linux-gnu) libcurl/8.7.1 OpenSSL/3.0.15 nghttp2/1.57.0
Release-Date: 2024-03-27
Protocols: file ftp ftps http https ipfs ipns mqtt tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile SSL threadsafe TLS-SRP UnixSockets

**Comment by Auroraxpm** [comment]
luci  是通用的 依赖你要自己解决

**Comment by Jonnyan404** [comment]
> luci 是通用的 依赖你要自己解决

PHP依赖不支持armv7l，估计得编译了，懒得折腾了，等换arm64设备之后再来试试的吧，感谢解答
