### ISSUE TITLE
Sing-box 的日志输出实在是太太太太长了，而且其日记文件会不断填满路由器 RAM

### ISSUE THREAD

**Issue by AngelSherry** [Thaolga/openwrt-nekobox#4]
如下图所示，当选择 Sing-box 作为后端并启动时，无论有没有开自动刷新，其输出都会因为没有被自动换行或者限制框体大小，导致**整个介面都会被 Sing-box 的输出日记弄到变形**且右边的元素无法点击。
![Screenshot From 2024-11-15 10-39-58](https://github.com/user-attachments/assets/da2f644b-2c09-4e4c-91f8-193d71deba8f)
![Screenshot From 2024-11-15 10-40-57](https://github.com/user-attachments/assets/6f6f176f-9950-40a0-8515-054667cb54a6)
![Screenshot From 2024-11-15 10-41-11](https://github.com/user-attachments/assets/0b17f1bc-ce57-4d3a-a3ff-ae5f822b8cb0)

另外，Sing-box 在 `/tmp/log/singbox_log.txt` 下輸出的**日志不会被自动清理，其不断增长最终会导致整个路由器的 RAM 被其日志塞满**。

![Screenshot From 2024-11-15 10-51-38](https://github.com/user-attachments/assets/e9ac2b40-117b-42ba-baf2-db35e4538045)

P.S 我这边通过写了个 `0 * * * * rm /tmp/log/singbox_log.txt` 的 Crontab 才能让它不吃完整个 RAM，不然只要一两天整个路由器的 RAM 就会被它的 RAM 填满且无法写入任何数据

**Comment by Auroraxpm** [comment]
你的日志路径搞错了 /var/log/singbox_log.txt才是日志路径  1000000字符会清空日志 别整体盯着日志看 日志是提供运行错误时判断问题用的运行正常没必要关注日志  你可以修改配置文件开头部分 "log": {
    "level": "error",限制日志输出

**Comment by Auroraxpm** [comment]
一般30M就会被清理

**Comment by Auroraxpm** [comment]
![photo_2024-11-15_11-42-40](https://github.com/user-attachments/assets/052ca4e8-a224-41cd-a106-27e59732e5ce)

**Comment by AngelSherry** [comment]
> 你的日志路径搞错了 /var/log/singbox_log.txt才是日志路径 1000000字符会清空日志 别整天盯着日志看 日志是提供运行错误时判断问题用的运行正常没必要关注日志 你可以修改配置文件开头部分 "log": { "level": "error",限制日志输出

![圖片](https://github.com/user-attachments/assets/379c5b5a-55ab-4f3c-90b3-984b08867655)
我这边的路由器因为 ROM 比较小，导致 /var 实际上是 /tmp 的软连结。目前观测到，只要 OpenWRT 不处于 nekobox 的那个主界面中（即那个切换模式+日志的介面），singbox_log.txt 只会越来越大。

前两天在只运行 nekobox 的情况下，singbox_log.txt大小达到了 200MB，最终把整个 202.09 MB 的路由器临时空间全部使用完，且并没有触发自动清理。

先在我已经删掉了 Crontab 中自动清理的命令，并在尝试复现中

**Comment by Auroraxpm** [comment]
修改/www/nekobox/fetch_logs.php   找到1000000位置修改 去掉一个0改为10万字符清理

**Comment by Auroraxpm** [comment]
![photo_2024-11-15_12-08-03](https://github.com/user-attachments/assets/44a003d7-d0e6-4620-90fc-851459de0d32)
info修改成error 限制日志输出

**Comment by AngelSherry** [comment]
> 修改/www/nekobox/fetch_logs.php 找到1000000位置修改 去掉一个0改为10万字符清理

为了方便测试，我特地保持日志的输出等级为 info

事实证明，**只要不在 OpenWRT 中访问 Nekobox 的主界面**，无论 /www/nekobox/fetch_logs.php 中的数值填多少，**都不会触发清理**。

而且目前一下午测试一下午后，singbox_log.txt 的大小已经达到了 31.2 MB，远高达上述提到的 30 MB，其大小还会不断增长。而且该日志确实会占用小容量设备的 /tmp 临时储存空间。
![Screenshot From 2024-11-15 16-13-31](https://github.com/user-attachments/assets/3ff8abb6-fda6-40a1-92b1-8b3acc77a57d)
![Screenshot From 2024-11-15 16-14-13](https://github.com/user-attachments/assets/ccfdd15c-71ce-4613-b586-8ffc4a3b4f97)

**Comment by Auroraxpm** [comment]
设置日志等级 你别用info了  info一秒2万字符你小内存吃不消

**Comment by AngelSherry** [comment]
日志自动清除失败似乎是由于这个错误引起的
```
<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in <b>/www/nekobox/fetch_logs.php</b> on line <b>21</b><br />
```

![圖片](https://github.com/user-attachments/assets/3a3864ff-387a-4207-b3cb-b080c61b9997)

**Comment by Auroraxpm** [comment]
等我推送新版

**Comment by Auroraxpm** [comment]
更新插件  添加定时清理日志
