### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Vancltkin** [Thaolga/openwrt-nekobox#5]
":0,"created_at":"2024-12-14T01:35:53Z","updated_at":"2024-12-14T01:36:06Z","browser_download_url":"https://github.com/Thaolga/openwrt-nekobox/releases/download/1.5.9/luci-app-nekobox_1.5.9-cn_all.ipk"}],"tarball_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/tarball/1.5.9","zipball_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/zipball/1.5.9","body":""}-en_all.ipk
curl: (3) nested brace in URL position 333:
https://github.com/Thaolga/openwrt-nekobox/releases/download/{"url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119","assets_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119/assets","upload_url":"https://uploads.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119/assets{?name,label}","html_url":"https://github.com/Thaolga/openwrt-nekobox/releases/tag/1.5.9","id":190737119,"author":{"login":"Auroraxpm","id":73517
Download failed!

**Comment by Auroraxpm** [comment]
The English version hasn't been pushed yet, it will be updated later

**Comment by Vancltkin** [comment]
> Английская версия пока не опубликована, она будет обновлена ​​позже.

0,"created_at":"2024-12-14T01:35:53Z","updated_at":"2024-12-14T01:36:06Z","browser_download_url":"https://github.com/Thaolga/openwrt-nekobox/releases/download/1.5.9/luci-app-nekobox_1.5.9-cn_all.ipk"}],"tarball_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/tarball/1.5.9","zipball_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/zipball/1.5.9","body":""}-cn_all.ipk
curl: (3) nested brace in URL position 333:
https://github.com/Thaolga/openwrt-nekobox/releases/download/{"url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119","assets_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119/assets","upload_url":"https://uploads.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119/assets{?name,label}","html_url":"https://github.com/Thaolga/openwrt-nekobox/releases/tag/1.5.9","id":190737119,"author":{"login":"Auroraxpm","id":73517
Download failed!

CN VERSION

**Comment by Vancltkin** [comment]
1.5.8 VERSION

curl: (3) nested brace in URL position 333:
https://github.com/Thaolga/openwrt-nekobox/releases/download/{"url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/189514991","assets_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/189514991/assets","upload_url":"https://uploads.github.com/repos/Thaolga/openwrt-nekobox/releases/189514991/assets{?name,label}","html_url":"https://github.com/Thaolga/openwrt-nekobox/releases/tag/1.5.8","id":189514991,"author":{"login":"Auroraxpm","id":73517
Download failed!

**Comment by Auroraxpm** [comment]
What is your download method?

**Comment by Auroraxpm** [comment]
The Chinese version has been pushed, and the English version will be later; downloading the English version will result in an error

**Comment by Vancltkin** [comment]
Я пробовал оба варианта bash и wget, также у вас нет у установке curl  это была первая ошибка, вторая это ошибка это ссылка на скачивание содержит артефакты

**Comment by Vancltkin** [comment]
> Китайская версия уже загружена, а английская версия будет позже; загрузка английской версии приведет к ошибке

я это понимаю , я устанавливал до этого 1.5.8 версию была проблема и сейчас вы выпустили обновление тоже проблема на 1.5.9

**Comment by Auroraxpm** [comment]
Are you installed in Chinese version?

**Comment by Vancltkin** [comment]
> У вас установлена ​​китайская версия?

нет, у меня выдает ошибку https://github.com/Thaolga/openwrt-nekobox/issues/5#issuecomment-2542656347

**Comment by Auroraxpm** [comment]
The English version has not been pushed yet, so you will encounter an error when downloading

**Comment by Vancltkin** [comment]
> Английская версия пока не загружена, поэтому при загрузке может возникнуть ошибка.

[cn_all.ipk](https://github.com/Thaolga/openwrt-nekobox/releases/download/1.5.9/luci-app-nekobox_1.5.9-cn_all.ipk%22%7D%5D,%22tarball_url%22:%22https://api.github.com/repos/Thaolga/openwrt-nekobox/tarball/1.5.9%22,%22zipball_url%22:%22https://api.github.com/repos/Thaolga/openwrt-nekobox/zipball/1.5.9%22,%22body%22:%22%22%7D-cn_all.ipk)
https://github.com/Thaolga/openwrt-nekobox/issues/5#issuecomment-2542656347

cn_all.ip

это cn версия

**Comment by Auroraxpm** [comment]
https://github.com/Thaolga/openwrt-nekobox/releases/download/1.5.9/luci-app-nekobox_1.5.9-cn_all.ipk

**Comment by Vancltkin** [comment]
Мой путь
1) opkg update
opkg install curl

2) я выполняю такой скрипт 
wget -O /root/nekobox.sh https://mirror.ghproxy.com/https://raw.githubusercontent.com/Thaolga/openwrt-nekobox/nekobox/nekobox.sh  && chmod 0755 /root/nekobox.sh && /root/nekobox.sh

3) там выбираю cn

4) Ошибка

":3,"created_at":"2024-12-14T01:35:53Z","updated_at":"2024-12-14T01:36:06Z","browser_download_url":"https://github.com/Thaolga/openwrt-nekobox/releases/download/1.5.9/luci-app-nekobox_1.5.9-cn_all.ipk"}],"tarball_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/tarball/1.5.9","zipball_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/zipball/1.5.9","body":""}-cn_all.ipk
curl: (3) nested brace in URL position 333:
https://github.com/Thaolga/openwrt-nekobox/releases/download/{"url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119","assets_url":"https://api.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119/assets","upload_url":"https://uploads.github.com/repos/Thaolga/openwrt-nekobox/releases/190737119/assets{?name,label}","html_url":"https://github.com/Thaolga/openwrt-nekobox/releases/tag/1.5.9","id":190737119,"author":{"login":"Auroraxpm","id":73517
Download failed!

**Comment by Vancltkin** [comment]
Я ещё попробовал вот так 

1) @OpenWrt:~# wget https://github.com/Thaolga/openwrt-nekobox/releases/download/1.5.9/luci-app-nekobox_1.5.9-cn_all.ipk
2)@OpenWrt:~# opkg install /tmp/luci-app-nekobox_1.5.9-cn_all.ipk
3)restart
4)
![{E6CAC9BC-8F58-46FE-9481-855CBE7F54B2}](https://github.com/user-attachments/assets/b7336399-94e5-4082-9bd7-461899aeacd5)

**Comment by Auroraxpm** [comment]
https://github.com/Thaolga/openwrt-nekobox/releases            Download IPK for installation from the page

**Comment by Auroraxpm** [comment]
Ensure that the Luci version is above version 22

**Comment by Vancltkin** [comment]
Я могу установить вот так

root@OpenWrt:~# opkg install --force-depends /tmp/luci-app-nekobox_1.5.9-en_all.ipk
Installing luci-app-nekobox (1.5.9-en) to root...
Installing kmod-tun (5.15.162-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/targets/mediatek/filogic/packages/kmod-tun_5.15.162-1_aarch64_cortex-a53.ipk
Installing terminfo (6.4-2) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/base/terminfo_6.4-2_aarch64_cortex-a53.ipk
Installing libncurses6 (6.4-2) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/base/libncurses6_6.4-2_aarch64_cortex-a53.ipk
Installing libreadline8 (8.2-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/base/libreadline8_8.2-1_aarch64_cortex-a53.ipk
Installing bash (5.2.15-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/bash_5.2.15-1_aarch64_cortex-a53.ipk
Installing libnghttp2-14 (1.57.0-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/libnghttp2-14_1.57.0-1_aarch64_cortex-a53.ipk
Installing libcurl4 (8.7.1-r1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/libcurl4_8.7.1-r1_aarch64_cortex-a53.ipk
Installing curl (8.7.1-r1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/curl_8.7.1-r1_aarch64_cortex-a53.ipk
Installing jq (1.6-2) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/jq_1.6-2_aarch64_cortex-a53.ipk
Installing libpcre2 (10.42-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/base/libpcre2_10.42-1_aarch64_cortex-a53.ipk
Installing zlib (1.2.13-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/base/zlib_1.2.13-1_aarch64_cortex-a53.ipk
Installing libxml2 (2.12.5-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/base/libxml2_2.12.5-1_aarch64_cortex-a53.ipk
Installing zoneinfo-core (2023c-2) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/zoneinfo-core_2023c-2_aarch64_cortex-a53.ipk
Installing php8 (8.2.26-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/php8_8.2.26-1_aarch64_cortex-a53.ipk
Installing libstdcpp6 (12.3.0-4) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/targets/mediatek/filogic/packages/libstdcpp6_12.3.0-4_aarch64_cortex-a53.ipk
Installing php8-cgi (8.2.26-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/php8-cgi_8.2.26-1_aarch64_cortex-a53.ipk
Installing php8-mod-curl (8.2.26-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/php8-mod-curl_8.2.26-1_aarch64_cortex-a53.ipk
Installing icu73 (73.2-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/icu73_73.2-1_aarch64_cortex-a53.ipk
Installing php8-mod-intl (8.2.26-1) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/php8-mod-intl_8.2.26-1_aarch64_cortex-a53.ipk
Installing zoneinfo-asia (2023c-2) to root...
Downloading https://downloads.openwrt.org/releases/23.05.4/packages/aarch64_cortex-a53/packages/zoneinfo-asia_2023c-2_aarch64_cortex-a53.ipk
Configuring terminfo.
Configuring jq.
Configuring kmod-tun.
Configuring libncurses6.
Configuring libreadline8.
Configuring bash.
Configuring zoneinfo-core.
Configuring zoneinfo-asia.
Configuring libpcre2.
Configuring zlib.
Configuring libxml2.
Configuring php8.
Configuring libnghttp2-14.
Configuring libcurl4.
Configuring php8-mod-curl.
Configuring libstdcpp6.
Configuring php8-cgi.
Configuring curl.
Configuring icu73.
Configuring php8-mod-intl.
Configuring luci-app-nekobox.
[ 17:52:41 ] - Checking Files...
[ 17:52:41 ] - Old Files Not Detected, Checking Files
[ 17:52:42 ] Starting Neko v.1.5.9
[ 17:52:42 ] - First Install Detected.
[ 17:52:42 ] Neko Not Running


Но после этого получаю ошибку в UI 

![{098434BB-9C48-4E82-A073-739A567B3AAD}](https://github.com/user-attachments/assets/01e2793d-5b2f-426b-ab95-bd99e55ee1c6)
